apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- alertmanager-serviceMonitor.yaml                                 
- kubernetesControlPlane-serviceMonitorKubeScheduler.yaml
- grafana-serviceMonitor.yaml                                      
- kubeStateMetrics-serviceMonitor.yaml
- kubernetesControlPlane-serviceMonitorApiserver.yaml             
- kubernetesControlPlane-serviceMonitorCoreDNS.yaml              
- nodeExporter-serviceMonitor.yaml
- kubernetesControlPlane-serviceMonitorKubeControllerManager.yaml 
- prometheusOperator-serviceMonitor.yaml
- kubernetesControlPlane-serviceMonitorKubelet.yaml               
- prometheus-serviceMonitor.yaml
