apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app.kubernetes.io/name: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio-external
spec:
  type: LoadBalancer
  ports:
    - port: 9999
      targetPort: 9999
      protocol: TCP
  selector:
    app.kubernetes.io/name: minio