apiVersion: monitoring.coreos.com/v1
kind: ThanosRuler
metadata:
  labels:
    app.kubernetes.io/name: thanos-ruler
  name: thanos-ruler
  namespace: monitoring
spec:
  image: quay.io/thanos/thanos:v0.25.1
  queryEndpoints:
  - dnssrv+_http._tcp.thanos-query.monitoring.svc.cluster.local
  ruleSelector:
    matchLabels:
      role: thanos-example