apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- crd
- operator
- prometheus
- alert-manager
- grafana 
- node-exporter
- kube-state-metrics
- service-monitor
- prometheus-rule
# - sample-instument-app
# - minio
- thanos