apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kubeStateMetrics-clusterRoleBinding.yaml  
- kubeStateMetrics-networkPolicy.yaml   
- kubeStateMetrics-clusterRole.yaml           
- kubeStateMetrics-service.yaml
- kubeStateMetrics-deployment.yaml         
- kubeStateMetrics-serviceAccount.yaml

