apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - name: data
      port: 9000
      targetPort: 9000
      protocol: TCP
    - name: ui
      port: 37131
      targetPort: 37131
      protocol: TCP
  selector:
    app: minio
    