apiVersion: v1
data:
  opsgenie: N2JhZGZhMzktYzI4ZS00MDdiLWE5ZjMtNjczZjY3Y2UzNjM0
  slack: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAxRU5MNUVXVkEvQjA0RVZUMkRZRzUvR204a1VwTlhCN1FCblpEUFNFS21DODlL
kind: Secret
metadata:
  name: alertmanager-secret
