apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  labels:
    alertmanagerConfig: alertmanager-config
spec: 

#  route:
#     group_by: ['job']
#     group_wait: 30s
#     group_interval: 5m
#     repeat_interval: 12h
#     receiver: 'webhook'

#     routes:

#         - matchers:
#             - severity="warning"
#           receiver: opsgenie
#           routes:
#             - matchers:
#                 - severity="critical"
#               receiver: opsgenie
  route:
    group_by: ['job']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 12h
    receiver: 'opsgenie'

  receivers:
  - name: 'opsgenie'
    opsgenieConfigs:
    - apiURL: "https://papergrid.app.opsgenie.com/"
      apiKey:
        key: opsgenie
        name: alertmanager-secret


