apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 0.24.0
  name: alertmanager-main
  namespace: monitoring
stringData:
  alertmanager.yaml: |-
      global:
        slack_api_url: "https://hooks.slack.com/services/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"
      route:
        group_by: ['alertname', 'cluster', 'service']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 3h
        receiver: opsgenie
        routes:
          - matchers:
              - severity="warning"
            receiver: opsgenie
            routes:
              - matchers:
                  - severity="critical"
                receiver: opsgenie

      # inhibit_rules:
      #   - source_matchers: [severity="critical"]
      #     target_matchers: [severity="warning"]
      #     # Apply inhibition if the alertname is the same.
      #     # CAUTION:
      #     #   If all label names listed in `equal` are missing
      #     #   from both the source and target alerts,
      #     #   the inhibition rule will apply!
      #     equal: [alertname, cluster, service]


      receivers:
        - name: 'web.hook'
          webhook_configs:
            - url: 'http://127.0.0.1:5001/'
        - name: 'opsgenie'
          opsgenie_config:
              send_resolved: true 
              api_key: "7badfa39-c28e-407b-a9f3-673f67ce3634"
              api_url: "https://papergrid.app.opsgenie.com/"

type: Opaque
