apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  labels:
    alertmanagerConfig: alertmanager-config
spec: 
  route:
    groupBy: ['alertname','job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'opsgenie'
    matchers:
      name: myname

    routes:
    - receiver: 'opsgenie'
      group_wait: 10s
      matchers:
      - name: severity 
        regex: true
        values: "critical|warning"
    - receiver: 'slack'
      group_wait: 10s
      matchers:
      - name: severity 
        regex: true
        values: "critical|warning"

  receivers:
  - name: 'opsgenie'
    opsgenieConfigs:
    - apiURL: "https://papergrid.app.opsgenie.com/"
      apiKey:
        key: opsgenie
        name: alertmanager-secret
      
  - name: 'slack'
    slackConfigs:
    - sendResolved: true
      apiURL:
        key: slack
        name: alertmanager-secret
      channel: '#ci-cd-notifications'
      text: |-
        {{ range .Alerts }}{{ .Annotations.summary }}
        {{ .Annotations.description }}
        {{ .Annotations.message }}
        {{ end }}

