apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  labels:
    alertmanagerConfig: alertmanager-config
spec:
  route:
    group_by: ['alertname', 'cluster', 'service']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 3h
    receiver: 'opsgenie'
    routes:
      - matchers:
          - severity="warning"
        receiver: opsgenie
        routes:
          - matchers:
              - severity="critical"
            receiver: opsgenie

  receivers:
  - name: 'opsgenie'
    opsgenieConfigs:
    - apiURL: "https://papergrid.app.opsgenie.com/"
      apiKey:
        key: opsgenie
        name: alertmanager-secret

      




