apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  labels:
    alertmanagerConfig: alertmanager-config
spec: 
  route:
    groupBy: ['alertname','job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'opsgenie'
    routes:
    - receiver: 'opsgenie'
      group_wait: 10s
      matchers:
      - severity=~"critical|warning"

  receivers:
  - name: 'opsgenie'
    opsgenieConfigs:
    - apiURL: "https://papergrid.app.opsgenie.com/"
      apiKey:
        key: opsgenie
        name: alertmanager-secret