apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  labels:
    alertmanagerConfig: alertmanager-config
spec: 
  route:
    groupBy: ['alertname','job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'opsgenie'

    routes:
    - receiver: 'opsgenie'
      group_wait: 10s
      matchers:
      - matchType: =~
        name: severity
        values: critical|warning

    - receiver: 'slack'
      group_wait: 10s
      matchers:
      - matchType: =
        name: severity
        values: critical|warning

    - matchers:
      - matchType: =
        name: alertname
        value: Watchdog
      receiver: asdf


  receivers:
  - name: 'opsgenie'
    opsgenieConfigs:
    - apiURL: "https://papergrid.app.opsgenie.com/"
      apiKey:
        key: opsgenie
        name: alertmanager-secret
      
  - name: 'slack'
    slackConfigs:
    - sendResolved: true
      apiURL:
        key: slack
        name: alertmanager-secret
      channel: '#ci-cd-notifications'
      text: |-
        {{ range .Alerts }}{{ .Annotations.summary }}
        {{ .Annotations.description }}
        {{ .Annotations.message }}
        {{ end }}

