apiVersion: v1
data:
  opsgenie: N2JhZGZhMzktYzI4ZS00MDdiLWE5ZjMtNjczZjY3Y2UzNjM0
  slack: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAxRU5MNUVXVkEvQjA0SDZCM1VHSFkvUlg5SzU5d2FkeUNMWXhCQ0tjZEE4NWNECg==
kind: Secret
type: Opaque
metadata:
  name: alertmanager-secret
  namespace: monitoring
